import { render, screen } from '@testing-library/react';
import ConnectionsPage from '../src/pages/connections/index';
import '@testing-library/jest-dom';

jest.mock('next/router', () => require('next-router-mock'));

describe('Connections Page', () => {
  it('renders heading', () => {
    render(
      <ConnectionsPage
        data={mockData}
        departure={'Basel'}
        destination={'Zurich'}
      />
    );

    const heading = screen.getByRole('heading');

    expect(heading).toBeInTheDocument();
  });

  it('renders link', () => {
    render(
      <ConnectionsPage
        data={mockData}
        departure={'Basel'}
        destination={'Zurich'}
      />
    );

    const link = screen.getByTestId('connections-link');

    expect(link).toBeInTheDocument();
  });
});

var mockData = {
  connections: [
    {
      from: {
        station: {
          id: '8500010',
          name: 'Basel SBB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.547412,
            y: 7.589577,
          },
          distance: null,
        },
        arrival: null,
        arrivalTimestamp: null,
        departure: '2023-02-20T20:33:00+0100',
        departureTimestamp: 1676921580,
        delay: 0,
        platform: '6',
        prognosis: {
          platform: null,
          arrival: null,
          departure: '2023-02-20T20:33:00+0100',
          capacity1st: null,
          capacity2nd: null,
        },
        realtimeAvailability: null,
        location: {
          id: '8500010',
          name: 'Basel SBB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.547412,
            y: 7.589577,
          },
          distance: null,
        },
      },
      to: {
        station: {
          id: '8503000',
          name: 'Zürich HB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.377847,
            y: 8.540502,
          },
          distance: null,
        },
        arrival: '2023-02-20T21:26:00+0100',
        arrivalTimestamp: 1676924760,
        departure: null,
        departureTimestamp: null,
        delay: null,
        platform: '5',
        prognosis: {
          platform: null,
          arrival: null,
          departure: null,
          capacity1st: null,
          capacity2nd: null,
        },
        realtimeAvailability: null,
        location: {
          id: '8503000',
          name: 'Zürich HB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.377847,
            y: 8.540502,
          },
          distance: null,
        },
      },
      duration: '00d00:53:00',
      transfers: 0,
      service: null,
      products: ['IC 3'],
      capacity1st: null,
      capacity2nd: null,
      sections: [
        {
          journey: {
            name: null,
            category: 'IC',
            subcategory: null,
            categoryCode: null,
            number: '3',
            operator: 'SBB',
            to: 'Chur',
            passList: [
              {
                station: {
                  id: '8500010',
                  name: 'Basel SBB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.547412,
                    y: 7.589577,
                  },
                  distance: null,
                },
                arrival: null,
                arrivalTimestamp: null,
                departure: '2023-02-20T20:33:00+0100',
                departureTimestamp: 1676921580,
                delay: 0,
                platform: '6',
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T20:33:00+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8500010',
                  name: 'Basel SBB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.547412,
                    y: 7.589577,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '0000175',
                  name: 'Hauenstein-Basistunnel',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.401131,
                    y: 7.904324,
                  },
                  distance: null,
                },
                arrival: null,
                arrivalTimestamp: null,
                departure: null,
                departureTimestamp: null,
                delay: null,
                platform: null,
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T20:28:06+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '0000175',
                  name: 'Hauenstein-Basistunnel',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.401131,
                    y: 7.904324,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '8503000',
                  name: 'Zürich HB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.377847,
                    y: 8.540502,
                  },
                  distance: null,
                },
                arrival: '2023-02-20T21:26:00+0100',
                arrivalTimestamp: 1676924760,
                departure: null,
                departureTimestamp: null,
                delay: 0,
                platform: '5',
                prognosis: {
                  platform: null,
                  arrival: '2023-02-20T21:26:00+0100',
                  departure: null,
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8503000',
                  name: 'Zürich HB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.377847,
                    y: 8.540502,
                  },
                  distance: null,
                },
              },
            ],
            capacity1st: null,
            capacity2nd: null,
          },
          walk: null,
          departure: {
            station: {
              id: '8500010',
              name: 'Basel SBB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.547412,
                y: 7.589577,
              },
              distance: null,
            },
            arrival: null,
            arrivalTimestamp: null,
            departure: '2023-02-20T20:33:00+0100',
            departureTimestamp: 1676921580,
            delay: 0,
            platform: '6',
            prognosis: {
              platform: null,
              arrival: null,
              departure: '2023-02-20T20:33:00+0100',
              capacity1st: null,
              capacity2nd: null,
            },
            realtimeAvailability: null,
            location: {
              id: '8500010',
              name: 'Basel SBB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.547412,
                y: 7.589577,
              },
              distance: null,
            },
          },
          arrival: {
            station: {
              id: '8503000',
              name: 'Zürich HB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.377847,
                y: 8.540502,
              },
              distance: null,
            },
            arrival: '2023-02-20T21:26:00+0100',
            arrivalTimestamp: 1676924760,
            departure: null,
            departureTimestamp: null,
            delay: 0,
            platform: '5',
            prognosis: {
              platform: null,
              arrival: '2023-02-20T21:26:00+0100',
              departure: null,
              capacity1st: null,
              capacity2nd: null,
            },
            realtimeAvailability: null,
            location: {
              id: '8503000',
              name: 'Zürich HB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.377847,
                y: 8.540502,
              },
              distance: null,
            },
          },
        },
      ],
    },
    {
      from: {
        station: {
          id: '8500010',
          name: 'Basel SBB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.547412,
            y: 7.589577,
          },
          distance: null,
        },
        arrival: null,
        arrivalTimestamp: null,
        departure: '2023-02-20T20:43:00+0100',
        departureTimestamp: 1676922180,
        delay: 0,
        platform: '7',
        prognosis: {
          platform: null,
          arrival: null,
          departure: '2023-02-20T20:43:00+0100',
          capacity1st: null,
          capacity2nd: null,
        },
        realtimeAvailability: null,
        location: {
          id: '8500010',
          name: 'Basel SBB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.547412,
            y: 7.589577,
          },
          distance: null,
        },
      },
      to: {
        station: {
          id: '8503000',
          name: 'Zürich HB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.377847,
            y: 8.540502,
          },
          distance: null,
        },
        arrival: '2023-02-20T21:52:00+0100',
        arrivalTimestamp: 1676926320,
        departure: null,
        departureTimestamp: null,
        delay: null,
        platform: '17',
        prognosis: {
          platform: null,
          arrival: null,
          departure: null,
          capacity1st: null,
          capacity2nd: null,
        },
        realtimeAvailability: null,
        location: {
          id: '8503000',
          name: 'Zürich HB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.377847,
            y: 8.540502,
          },
          distance: null,
        },
      },
      duration: '00d01:09:00',
      transfers: 0,
      service: null,
      products: ['IR 37'],
      capacity1st: null,
      capacity2nd: null,
      sections: [
        {
          journey: {
            name: null,
            category: 'IR',
            subcategory: null,
            categoryCode: null,
            number: '37',
            operator: 'SBB',
            to: 'Zürich HB',
            passList: [
              {
                station: {
                  id: '8500010',
                  name: 'Basel SBB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.547412,
                    y: 7.589577,
                  },
                  distance: null,
                },
                arrival: null,
                arrivalTimestamp: null,
                departure: '2023-02-20T20:43:00+0100',
                departureTimestamp: 1676922180,
                delay: 0,
                platform: '7',
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T20:43:00+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8500010',
                  name: 'Basel SBB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.547412,
                    y: 7.589577,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '8500023',
                  name: 'Liestal',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.484462,
                    y: 7.731377,
                  },
                  distance: null,
                },
                arrival: '2023-02-20T20:53:00+0100',
                arrivalTimestamp: 1676922780,
                departure: '2023-02-20T20:54:00+0100',
                departureTimestamp: 1676922840,
                delay: 1,
                platform: null,
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T20:55:00+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8500023',
                  name: 'Liestal',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.484462,
                    y: 7.731377,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '8500026',
                  name: 'Sissach',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.462752,
                    y: 7.812039,
                  },
                  distance: null,
                },
                arrival: '2023-02-20T21:01:00+0100',
                arrivalTimestamp: 1676923260,
                departure: '2023-02-20T21:01:00+0100',
                departureTimestamp: 1676923260,
                delay: 0,
                platform: null,
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T21:01:00+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8500026',
                  name: 'Sissach',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.462752,
                    y: 7.812039,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '8502113',
                  name: 'Aarau',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.391361,
                    y: 8.051284,
                  },
                  distance: null,
                },
                arrival: '2023-02-20T21:20:00+0100',
                arrivalTimestamp: 1676924400,
                departure: '2023-02-20T21:23:00+0100',
                departureTimestamp: 1676924580,
                delay: 0,
                platform: null,
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T21:23:00+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8502113',
                  name: 'Aarau',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.391361,
                    y: 8.051284,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '8502119',
                  name: 'Lenzburg',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.391199,
                    y: 8.170394,
                  },
                  distance: null,
                },
                arrival: '2023-02-20T21:30:00+0100',
                arrivalTimestamp: 1676925000,
                departure: '2023-02-20T21:30:00+0100',
                departureTimestamp: 1676925000,
                delay: 1,
                platform: null,
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T21:31:00+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8502119',
                  name: 'Lenzburg',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.391199,
                    y: 8.170394,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '8503000',
                  name: 'Zürich HB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.377847,
                    y: 8.540502,
                  },
                  distance: null,
                },
                arrival: '2023-02-20T21:52:00+0100',
                arrivalTimestamp: 1676926320,
                departure: null,
                departureTimestamp: null,
                delay: 0,
                platform: '17',
                prognosis: {
                  platform: null,
                  arrival: '2023-02-20T21:52:00+0100',
                  departure: null,
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8503000',
                  name: 'Zürich HB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.377847,
                    y: 8.540502,
                  },
                  distance: null,
                },
              },
            ],
            capacity1st: null,
            capacity2nd: null,
          },
          walk: null,
          departure: {
            station: {
              id: '8500010',
              name: 'Basel SBB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.547412,
                y: 7.589577,
              },
              distance: null,
            },
            arrival: null,
            arrivalTimestamp: null,
            departure: '2023-02-20T20:43:00+0100',
            departureTimestamp: 1676922180,
            delay: 0,
            platform: '7',
            prognosis: {
              platform: null,
              arrival: null,
              departure: '2023-02-20T20:43:00+0100',
              capacity1st: null,
              capacity2nd: null,
            },
            realtimeAvailability: null,
            location: {
              id: '8500010',
              name: 'Basel SBB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.547412,
                y: 7.589577,
              },
              distance: null,
            },
          },
          arrival: {
            station: {
              id: '8503000',
              name: 'Zürich HB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.377847,
                y: 8.540502,
              },
              distance: null,
            },
            arrival: '2023-02-20T21:52:00+0100',
            arrivalTimestamp: 1676926320,
            departure: null,
            departureTimestamp: null,
            delay: 0,
            platform: '17',
            prognosis: {
              platform: null,
              arrival: '2023-02-20T21:52:00+0100',
              departure: null,
              capacity1st: null,
              capacity2nd: null,
            },
            realtimeAvailability: null,
            location: {
              id: '8503000',
              name: 'Zürich HB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.377847,
                y: 8.540502,
              },
              distance: null,
            },
          },
        },
      ],
    },
    {
      from: {
        station: {
          id: '8500010',
          name: 'Basel SBB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.547412,
            y: 7.589577,
          },
          distance: null,
        },
        arrival: null,
        arrivalTimestamp: null,
        departure: '2023-02-20T21:06:00+0100',
        departureTimestamp: 1676923560,
        delay: 0,
        platform: '5',
        prognosis: {
          platform: null,
          arrival: null,
          departure: '2023-02-20T21:06:00+0100',
          capacity1st: null,
          capacity2nd: null,
        },
        realtimeAvailability: null,
        location: {
          id: '8500010',
          name: 'Basel SBB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.547412,
            y: 7.589577,
          },
          distance: null,
        },
      },
      to: {
        station: {
          id: '8503000',
          name: 'Zürich HB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.377847,
            y: 8.540502,
          },
          distance: null,
        },
        arrival: '2023-02-20T22:00:00+0100',
        arrivalTimestamp: 1676926800,
        departure: null,
        departureTimestamp: null,
        delay: null,
        platform: '10',
        prognosis: {
          platform: null,
          arrival: null,
          departure: null,
          capacity1st: null,
          capacity2nd: null,
        },
        realtimeAvailability: null,
        location: {
          id: '8503000',
          name: 'Zürich HB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.377847,
            y: 8.540502,
          },
          distance: null,
        },
      },
      duration: '00d00:54:00',
      transfers: 0,
      service: null,
      products: ['ICE'],
      capacity1st: null,
      capacity2nd: null,
      sections: [
        {
          journey: {
            name: null,
            category: 'ICE',
            subcategory: null,
            categoryCode: null,
            number: null,
            operator: 'SBB',
            to: 'Zürich HB',
            passList: [
              {
                station: {
                  id: '8500010',
                  name: 'Basel SBB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.547412,
                    y: 7.589577,
                  },
                  distance: null,
                },
                arrival: null,
                arrivalTimestamp: null,
                departure: '2023-02-20T21:06:00+0100',
                departureTimestamp: 1676923560,
                delay: 0,
                platform: '5',
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T21:06:00+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8500010',
                  name: 'Basel SBB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.547412,
                    y: 7.589577,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '0000175',
                  name: 'Hauenstein-Basistunnel',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.401131,
                    y: 7.904324,
                  },
                  distance: null,
                },
                arrival: null,
                arrivalTimestamp: null,
                departure: null,
                departureTimestamp: null,
                delay: null,
                platform: null,
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T20:28:06+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '0000175',
                  name: 'Hauenstein-Basistunnel',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.401131,
                    y: 7.904324,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '8503000',
                  name: 'Zürich HB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.377847,
                    y: 8.540502,
                  },
                  distance: null,
                },
                arrival: '2023-02-20T22:00:00+0100',
                arrivalTimestamp: 1676926800,
                departure: null,
                departureTimestamp: null,
                delay: 0,
                platform: '10',
                prognosis: {
                  platform: null,
                  arrival: '2023-02-20T22:00:00+0100',
                  departure: null,
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8503000',
                  name: 'Zürich HB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.377847,
                    y: 8.540502,
                  },
                  distance: null,
                },
              },
            ],
            capacity1st: null,
            capacity2nd: null,
          },
          walk: null,
          departure: {
            station: {
              id: '8500010',
              name: 'Basel SBB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.547412,
                y: 7.589577,
              },
              distance: null,
            },
            arrival: null,
            arrivalTimestamp: null,
            departure: '2023-02-20T21:06:00+0100',
            departureTimestamp: 1676923560,
            delay: 0,
            platform: '5',
            prognosis: {
              platform: null,
              arrival: null,
              departure: '2023-02-20T21:06:00+0100',
              capacity1st: null,
              capacity2nd: null,
            },
            realtimeAvailability: null,
            location: {
              id: '8500010',
              name: 'Basel SBB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.547412,
                y: 7.589577,
              },
              distance: null,
            },
          },
          arrival: {
            station: {
              id: '8503000',
              name: 'Zürich HB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.377847,
                y: 8.540502,
              },
              distance: null,
            },
            arrival: '2023-02-20T22:00:00+0100',
            arrivalTimestamp: 1676926800,
            departure: null,
            departureTimestamp: null,
            delay: 0,
            platform: '10',
            prognosis: {
              platform: null,
              arrival: '2023-02-20T22:00:00+0100',
              departure: null,
              capacity1st: null,
              capacity2nd: null,
            },
            realtimeAvailability: null,
            location: {
              id: '8503000',
              name: 'Zürich HB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.377847,
                y: 8.540502,
              },
              distance: null,
            },
          },
        },
      ],
    },
    {
      from: {
        station: {
          id: '8500010',
          name: 'Basel SBB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.547412,
            y: 7.589577,
          },
          distance: null,
        },
        arrival: null,
        arrivalTimestamp: null,
        departure: '2023-02-20T21:11:00+0100',
        departureTimestamp: 1676923860,
        delay: 0,
        platform: '4',
        prognosis: {
          platform: null,
          arrival: null,
          departure: '2023-02-20T21:11:00+0100',
          capacity1st: null,
          capacity2nd: null,
        },
        realtimeAvailability: null,
        location: {
          id: '8500010',
          name: 'Basel SBB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.547412,
            y: 7.589577,
          },
          distance: null,
        },
      },
      to: {
        station: {
          id: '8503000',
          name: 'Zürich HB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.377847,
            y: 8.540502,
          },
          distance: null,
        },
        arrival: '2023-02-20T22:24:00+0100',
        arrivalTimestamp: 1676928240,
        departure: null,
        departureTimestamp: null,
        delay: null,
        platform: '16',
        prognosis: {
          platform: null,
          arrival: null,
          departure: null,
          capacity1st: null,
          capacity2nd: null,
        },
        realtimeAvailability: null,
        location: {
          id: '8503000',
          name: 'Zürich HB',
          score: null,
          coordinate: {
            type: 'WGS84',
            x: 47.377847,
            y: 8.540502,
          },
          distance: null,
        },
      },
      duration: '00d01:13:00',
      transfers: 0,
      service: null,
      products: ['IR 36'],
      capacity1st: null,
      capacity2nd: null,
      sections: [
        {
          journey: {
            name: null,
            category: 'IR',
            subcategory: null,
            categoryCode: null,
            number: '36',
            operator: 'SBB',
            to: 'Zürich HB',
            passList: [
              {
                station: {
                  id: '8500010',
                  name: 'Basel SBB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.547412,
                    y: 7.589577,
                  },
                  distance: null,
                },
                arrival: null,
                arrivalTimestamp: null,
                departure: '2023-02-20T21:11:00+0100',
                departureTimestamp: 1676923860,
                delay: 0,
                platform: '4',
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T21:11:00+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8500010',
                  name: 'Basel SBB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.547412,
                    y: 7.589577,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '8500301',
                  name: 'Rheinfelden',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.551217,
                    y: 7.792175,
                  },
                  distance: null,
                },
                arrival: '2023-02-20T21:24:00+0100',
                arrivalTimestamp: 1676924640,
                departure: '2023-02-20T21:25:00+0100',
                departureTimestamp: 1676924700,
                delay: 0,
                platform: null,
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T21:25:00+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8500301',
                  name: 'Rheinfelden',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.551217,
                    y: 7.792175,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '8500320',
                  name: 'Stein-Säckingen',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.541603,
                    y: 7.948855,
                  },
                  distance: null,
                },
                arrival: '2023-02-20T21:34:00+0100',
                arrivalTimestamp: 1676925240,
                departure: '2023-02-20T21:35:00+0100',
                departureTimestamp: 1676925300,
                delay: 0,
                platform: null,
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T21:35:00+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8500320',
                  name: 'Stein-Säckingen',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.541603,
                    y: 7.948855,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '8500305',
                  name: 'Frick',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.50735,
                    y: 8.013103,
                  },
                  distance: null,
                },
                arrival: '2023-02-20T21:41:00+0100',
                arrivalTimestamp: 1676925660,
                departure: '2023-02-20T21:42:00+0100',
                departureTimestamp: 1676925720,
                delay: 0,
                platform: null,
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T21:42:00+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8500305',
                  name: 'Frick',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.50735,
                    y: 8.013103,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '8500309',
                  name: 'Brugg AG',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.480859,
                    y: 8.208855,
                  },
                  distance: null,
                },
                arrival: '2023-02-20T21:57:00+0100',
                arrivalTimestamp: 1676926620,
                departure: '2023-02-20T22:00:00+0100',
                departureTimestamp: 1676926800,
                delay: 0,
                platform: null,
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T22:00:00+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8500309',
                  name: 'Brugg AG',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.480859,
                    y: 8.208855,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '8503504',
                  name: 'Baden',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.476417,
                    y: 8.307706,
                  },
                  distance: null,
                },
                arrival: '2023-02-20T22:07:00+0100',
                arrivalTimestamp: 1676927220,
                departure: '2023-02-20T22:08:00+0100',
                departureTimestamp: 1676927280,
                delay: 1,
                platform: null,
                prognosis: {
                  platform: null,
                  arrival: null,
                  departure: '2023-02-20T22:09:00+0100',
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8503504',
                  name: 'Baden',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.476417,
                    y: 8.307706,
                  },
                  distance: null,
                },
              },
              {
                station: {
                  id: '8503000',
                  name: 'Zürich HB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.377847,
                    y: 8.540502,
                  },
                  distance: null,
                },
                arrival: '2023-02-20T22:24:00+0100',
                arrivalTimestamp: 1676928240,
                departure: null,
                departureTimestamp: null,
                delay: 0,
                platform: '16',
                prognosis: {
                  platform: null,
                  arrival: '2023-02-20T22:24:00+0100',
                  departure: null,
                  capacity1st: null,
                  capacity2nd: null,
                },
                realtimeAvailability: null,
                location: {
                  id: '8503000',
                  name: 'Zürich HB',
                  score: null,
                  coordinate: {
                    type: 'WGS84',
                    x: 47.377847,
                    y: 8.540502,
                  },
                  distance: null,
                },
              },
            ],
            capacity1st: null,
            capacity2nd: null,
          },
          walk: null,
          departure: {
            station: {
              id: '8500010',
              name: 'Basel SBB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.547412,
                y: 7.589577,
              },
              distance: null,
            },
            arrival: null,
            arrivalTimestamp: null,
            departure: '2023-02-20T21:11:00+0100',
            departureTimestamp: 1676923860,
            delay: 0,
            platform: '4',
            prognosis: {
              platform: null,
              arrival: null,
              departure: '2023-02-20T21:11:00+0100',
              capacity1st: null,
              capacity2nd: null,
            },
            realtimeAvailability: null,
            location: {
              id: '8500010',
              name: 'Basel SBB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.547412,
                y: 7.589577,
              },
              distance: null,
            },
          },
          arrival: {
            station: {
              id: '8503000',
              name: 'Zürich HB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.377847,
                y: 8.540502,
              },
              distance: null,
            },
            arrival: '2023-02-20T22:24:00+0100',
            arrivalTimestamp: 1676928240,
            departure: null,
            departureTimestamp: null,
            delay: 0,
            platform: '16',
            prognosis: {
              platform: null,
              arrival: '2023-02-20T22:24:00+0100',
              departure: null,
              capacity1st: null,
              capacity2nd: null,
            },
            realtimeAvailability: null,
            location: {
              id: '8503000',
              name: 'Zürich HB',
              score: null,
              coordinate: {
                type: 'WGS84',
                x: 47.377847,
                y: 8.540502,
              },
              distance: null,
            },
          },
        },
      ],
    },
  ],
  from: {
    id: '8500010',
    name: 'Basel SBB',
    score: null,
    coordinate: {
      type: 'WGS84',
      x: 47.547412,
      y: 7.589577,
    },
    distance: null,
  },
  to: {
    id: '8503000',
    name: 'Zürich HB',
    score: null,
    coordinate: {
      type: 'WGS84',
      x: 47.377847,
      y: 8.540502,
    },
    distance: null,
  },
  stations: {
    from: [
      {
        id: '8500010',
        name: 'Basel SBB',
        score: null,
        coordinate: {
          type: 'WGS84',
          x: 47.547412,
          y: 7.589577,
        },
        distance: null,
      },
    ],
    to: [
      {
        id: '8503000',
        name: 'Zürich HB',
        score: null,
        coordinate: {
          type: 'WGS84',
          x: 47.377847,
          y: 8.540502,
        },
        distance: null,
      },
    ],
  },
} as any;
